backend:
  name: github
  repo: zineda/edadeniz
  branch: feat/profile-settings
  site_domain: edadeniz.com

site_url: https://edadeniz.com
display_url: https://edadeniz.com

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: settings
    label: Profile / Site settings
    format: toml
    files:
      - name: profile
        label: Profile
        file: data/profile.toml
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Headline / Bio, name: bio, widget: string }
          - { label: Previous roles, name: more_bio, widget: string }
          - { label: Profile photo, name: avatar, widget: image }
          - label: Social links
            name: social
            widget: object
            fields:
              - { label: GitHub, name: github, widget: string, required: false }
              - { label: LinkedIn, name: linkedin-square, widget: string, required: false }
              - { label: Twitter, name: twitter, widget: string, required: false }

  - name: pages
    label: Pages
    files:
      - name: home
        label: Home page
        file: content/_index.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: body, widget: markdown }

  - name: blog
    label: Blog posts
    folder: content/post
    create: true
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish date, name: date, widget: datetime }
      - { label: Description, name: description, widget: string, required: false }
      - { label: Categories, name: categories, widget: list, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Image width, name: image_width, widget: string, required: false }
      - { label: Draft, name: draft, widget: boolean, required: false, default: false }
      - { label: Content, name: body, widget: markdown }
